In [6]:
import numpy as np

arr = np.ones((9,9))

arr[1:8, 1:8] = np.array([0])
arr[2:7, 2:7] = np.array([1])
arr[3:6, 3:6] = np.array([0])
arr[4, 4] = np.array([1])
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 1., 1., 1., 1., 1., 0., 1.],
       [1., 0., 1., 0., 0., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 0., 0., 1., 0., 1.],
       [1., 0., 1., 1., 1., 1., 1., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [7]:
import numpy as np

arr = np.ones((9,9))

arr[1:8, 1:8] = np.zeros([7, 7])
arr[2:7, 2:7] = np.ones([5, 5])
arr[3:6, 3:6] = np.zeros([3, 3])
arr[4, 4] = np.ones([1,1])
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 1., 1., 1., 1., 1., 0., 1.],
       [1., 0., 1., 0., 0., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 0., 0., 1., 0., 1.],
       [1., 0., 1., 1., 1., 1., 1., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [13]:
import numpy as np

arr = np.ones((9,9))

arr[1:8, 1:8] = 0
arr[2:7, 2:7] = 1
arr[3:6, 3:6] = 0
arr[4, 4] = 1

print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 1. 1. 1. 1. 1. 0. 1.]
 [1. 0. 1. 0. 0. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 0. 0. 1. 0. 1.]
 [1. 0. 1. 1. 1. 1. 1. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]
