# 9.2 Numpy의 기초

In [2]:
x = [1, 3, 5]
x.mean()

AttributeError: 'list' object has no attribute 'mean'

In [3]:
import numpy as np

## Numpy 배열

- zeros()
 - 괄호 안에 입력된 숫자만큼의 원소를 생성하고 0으로 초기화
 
- array()
 - Numpy 형식으로 배열의 원소를 입력할 때는 반드시 리스트 형식으로 입력
 - x = np.array([1, 3, 5]) (O)
 - x = np.array(1, 3, 5)   (X)

### mean()
- 배열에 저장된 원소들의 평균값을 계산
 1. Numpy 모듈 가져오기
 2. 파이썬의 데이터형(예: 리스트)을 Numpy 형식으로 변환
 3. Numpy에서 제공하는 기능 수행(예: 평균)

In [4]:
x = np.array([1,3,5])
print(x.mean())

3.0


In [5]:
a = np.array([[1, 2, 3], [2, 3, 4]])

### shape 속성
 - print(x.shape)

In [6]:
print(x.shape)

(3,)


In [7]:
a = np.array([[1, 2, 3], [2, 3, 4]])
print(a.shape)

(2, 3)


### reshape()
 - 배열을 원하는 모양으로 생성

In [8]:
x = np.array([1, 3, 5, 7, 9, 11]).reshape(3, 2)
print(x)

[[ 1  3]
 [ 5  7]
 [ 9 11]]


### ones()
 - 배열을 1의 값들로 채움

In [9]:
y = np.ones([3, 4])
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 출력

In [10]:
x = np.array([[1, 3, 5], [2, 4, 6]])
print(x[1])
print(x[1].mean())  # 4.0 출력
print(x.mean()) # 3.5
print(x.shape) # (2,3)

[2 4 6]
4.0
3.5
(2, 3)


## Numpy 배열의 슬라이싱

### 파이썬의 2차원 리스트에서 모든 원소의 두 번째 원소들만 출력
 - 모든 원소에 대한 두 번째 항목의 내용을 따로 접근할 수 없음

In [11]:
list1 = [[1, 11], [2, 12], [3, 13]]
print(list[:][1])

TypeError: There are no type variables left in list[slice(None, None, None)]

### Numpy
 - 각각의 원소의 특정 인덱스 위치에 일괄적으로 접근 가능
 - 먼저 리스트를 Numpy 형식으로 변환 후 슬라이싱해야 함
 - 리스트이 인덱스는 반드시 정수나 슬라이스여야 함

In [12]:
import numpy as np
list1= [[1, 11], [2, 12], [3, 13]]
np_ary = np.array(list1)
print(np_ary[:, 1])

[11 12 13]


In [13]:
import numpy as np
list1 = [[1, 11], [2, 12], [3, 13]]
print(np.array(list1[:, 1]))
# 리스트를 Numpy로 변환해주기 전에 슬라이스를 한 것이 문제

TypeError: list indices must be integers or slices, not tuple

## Numpy를 이용한 연산 

### 파이썬 math 모듈의 sqrt()

In [14]:
import math
math.sqrt(2)

1.4142135623730951

In [15]:
math.sqrt([2, 3, 4])

TypeError: must be real number, not list

###  Numpy의 sqrt()

In [16]:
import numpy as np
np.sqrt([2, 3, 4])

array([1.41421356, 1.73205081, 2.        ])

In [17]:
import numpy as np
a = np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [18]:
import numpy as np
a = np.arange(15).reshape(3, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


## 제로 벡터와 제로 행렬 

### 0으로 초기화된 1차원의 zero_vector 생성

In [19]:
import numpy as np
zero_vector = np.zeros(3)
print(zero_vector)

[0. 0. 0.]


###  0으로 초기화된 (4X3) 형식의 2차원 배열 생성 

In [20]:
zero_matrix = np.zeros((4, 3))
print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### 0의 값을 갖는 5개의 1차원 배열 생성 

In [21]:
zero_vector = np.zeros(5)
zero_vector

array([0., 0., 0., 0., 0.])

In [22]:
import numpy as np
my_array = np.zeros(15).reshape(3, 5)
my_array += 4
my_array

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

## 전치 행렬
### 전치행렬
- 행과 열을 교환하여 얻어지는 행렬
- 행렬의 값들을 주대각선을 기준으로 위치를 바꾼 행렬을 의미

### transpose()
- 전치행렬로 변환 

In [23]:
import numpy as np
ary = np.array([[1,2], [3,4]])
print(ary.transpose())

[[1 3]
 [2 4]]


## 사칙연산
### 2개 배열에 대한 연산
- 2개 배열에 저장된 내용을 인덱스별로 계산
- 선형대수학의 사친연산과 동일하게 작동
- 곱셈도 같은 원리도 동작 

In [24]:
import numpy as np
x = np.array([1,2,3])
y = np.array([4,5,6])
z = x * y
print(z)

[ 4 10 18]


### Numpy 배열에 1을 더하면
- 각각의 원소에 1씩을 더할 수 있음

In [25]:
s = np.array([1,2,3])
t = s + 1
print(t)

[2 3 4]


## 인덱싱
### 인덱싱 

In [26]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(X[1])      # [4 5 6] 출력 (X배열의 인덱스 1번의 내용을 출력)
print(X[:, 1])   # [2 5 8] 출력 (각 1차원 배열의 1번의 내용을 출력)

[4 5 6]
[2 5 8]


In [27]:
X = np.array([[1,2,3], [4,5,6], [7,8,9]])
Y = np.array([[2,3,4], [5,6,7], [8,9,10]])
print(X[:, 1] + Y[:, 1])

[ 5 11 17]


In [28]:
a = np.array([10, 20, 30, 40, 50, 60, 70])
i = [1, 3, 5]
print(a[i])

[20 40 60]


In [32]:
import numpy as np
a = np.array([10, 20, 30, 40, 50, 60, 70])
b = a[1:6:2]
print('b:', b)
b[1] = 10
print('b:', b)
print('a:', a)
type(b)

b: [20 40 60]
b: [20 10 60]
a: [10 20 30 10 50 60 70]


numpy.ndarray

In [34]:
a = np.array([10,20,30,40,50,60,70])
b = a > 50

In [36]:
a = np.array([10,20,30,40,50,60,70])
b = a > 50
print(b)

[False False False False False  True  True]


In [38]:
ary = np.random.random(5)
print(ary)
print(np.all(ary >= 0.3))
print(np.any(ary > 0.7))

[0.38986596 0.32748739 0.64397201 0.46974621 0.00896816]
False
False


In [47]:
np.linspace(0, 12, 4)

array([ 0.,  4.,  8., 12.])

In [48]:
np.linspace(0, 12, 4, retstep=True)

(array([ 0.,  4.,  8., 12.]), 4.0)

In [49]:
np.linspace(0, 12, 3, endpoint=False)

array([0., 4., 8.])

In [51]:
np.logspace(np.log10(10), np.log10(100), 5)

array([ 10.        ,  17.7827941 ,  31.6227766 ,  56.23413252,
       100.        ])

In [52]:
np.logspace(1, 2, 5)

array([ 10.        ,  17.7827941 ,  31.6227766 ,  56.23413252,
       100.        ])

## Quiz 9.1

In [ ]:
a = np.array([[1, 2, 3], [2, 3, 4]])
print(a.shape)

## Quiz 9.2

In [ ]:
list1 = [[1, 11], [2, 12], [3, 13]]
print(list1[1][1])

## Quiz 9.3 

In [ ]:
import numpy as np
list1 = [[1, 11], [2, 12], [3, 13]]
print(np.array(list1[:][0]))

## Quiz 9.4

In [ ]:
import numpy as np
a = np.arange(15).reshape(3, 5)
print(a[1][1])

## Quiz 9.5

In [ ]:
x = [1, 2, 3]
y = [4, 5, 6]
z = x + y
print(z)

## Quiz 9.6

In [ ]:
import numpy as np
x = np.array([1,2,3])
y = np.array([4,5,6])
z = x + y
print(z)

## Quiz 9.7 

In [ ]:
import numpy as np
x = np.array([4,8,12])
y = np.array([2,4,6])
z = x / y
print(z)

## Quiz 9.8

In [39]:
import numpy as np
a = np.array([10, 20, 30, 40, 50, 60, 70])
b = a[1:6:2]
print('b:', b)
b[1] = 10
print('b:', b)
print('a:', a)

b: [20 40 60]
b: [20 10 60]
a: [10 20 30 10 50 60 70]


## Quiz 9.9

In [44]:
# height = [173, 168, 171, 189, 179]
# weight = [65.4, 59.2, 63.6, 88.4, 68.7]
# bmi = (weight/(height**2))*10000

import numpy as np
height = np.array([173, 168, 171, 189, 179])
weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmi = (weight/(height**2))*10000
print(bmi)


[21.85171573 20.97505669 21.75028214 24.7473475  21.44127836]


## Quiz 9.10

In [46]:
check = bmi > 21
print(check)

[ True False  True  True  True]
